image: node:latest

stages:
  - build
  - test
  - deploy

before_script:
  - rm -rf build
  - CI=false npm install

buildApp:
  stage: build
  tags:
    - hva
  artifacts:
    paths:
      - build/
  script:
    - echo "build started"
    - CI=false npm run build
    - echo "build completed"

testApp:
  stage: test
  tags:
    - hva
  only:
    changes:
      - "src/"
  script:
    - npm run test
    - echo "test completed"

deployApp:
  stage: deploy
  tags:
    - hva
  only:
    changes:
      - "src/"
  script:
    - git push heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/barber2u-fe-staging.git master
    - echo "the app is deployed"