image: node:latest

stages:
  - build
  - test
  - deploy

buildApp:
  stage: build
  tags:
    - hva
  only:
    changes:
      - "src/"
  artifacts:
    paths:
      - build/
  script:
    - node install -g node-gyp
    - echo "npm started"
    - npm install
    - echo "npm finished"
    - echo "build started"
    - npm run build
    - echo "build completed"

testApp:
  stage: test
  tags:
    - hva
  only:
    changes:
      - "src/"
  script:
    - npm run test
    - echo "test completed"

deployApp:
  stage: deploy
  tags:
    - hva
  only:
    changes:
      - "src/"
  script:
    - git push heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/barber2u-fe-staging.git master
    - echo "the app is deployed"