image: node:14

before_script:
  - npm install eslint-config-airbnb

stages:
  - build
  - test
  - deploy

buildApp:
  stage: build
  tags:
    - hva
  only:
    changes:
      - "src/"
  artifacts:
    paths:
      - build/
  script:
    - npm install
    - echo "build started"
    - npm run build
    - echo "build completed"

testApp:
  stage: test
  tags:
    - hva
  only:
    changes:
      - "src/"
  script:
    - npm install
    - npm run test -- --watchAll=false
    - echo "test completed"

deployApp:
  stage: deploy
  tags:
    - hva
  only:
    changes:
      - "src/"
  environment:
    name: production
    url: https://git.heroku.com/barber2u-fe.git
  script:
    - git push heroku master
    - echo "the app is deployed"
